require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/bundle
    - application.rb
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/requests/**/*.rb'
